# Generated by Django 5.0.4 on 2024-05-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inges_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='biografia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('f_estreno', models.DateField()),
                ('trailer', models.URLField()),
                ('e_produccion', models.URLField(max_length=100)),
                ('poster', models.URLField(max_length=100)),
                ('director', models.CharField(max_length=500)),
                ('protagonistas', models.ManyToManyField(to='inges_api.persona')),
            ],
        ),
    ]
