# Generated by Django 5.0.4 on 2024-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inges_api', '0003_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='protagonistas',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='protagonistas',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='e_produccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='f_estreno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='poster',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='trailer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serie',
            name='duracion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serie',
            name='e_produccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='f_estreno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serie',
            name='poster',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='trailer',
            field=models.CharField(max_length=200),
        ),
    ]
