# Generated by Django 5.0.4 on 2024-06-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inges_api', '0004_remove_pelicula_protagonistas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='director',
        ),
    ]
